# TODO: The "Show" form generated by scaffold generator didn't have a "Delete" link
# describe "Deleting a restaurant" do
#   it "destroys the movie and show the movie listing without the deleted restaurant" do
#     # Arrange
#     restaurant = Restaurant.create!(restaurant_attributes)

#     # Action
#     visit restaurant_path(restaurant)
#     click_link "Delete"

#     # Assert
#     expect(current_path).to eq(restaurants.path)
#     expect(page).not_to have_text(restaurant.name)

#     expect(page).to have_text("Restaurant successfully deleted!")
#   end
# end